name         'fortin-utils'
version      '1.0.0'
author       'alexander.fortin@gmail.com'
license      'Apache License, Version 2.0'
summary      'Puppet helper classes'
description  'Puppet helper classes'
project_page 'https://github.com/shaftoe/puppet-utils'
source       'https://github.com/shaftoe/puppet-utils.git'
dependency   'puppetlabs/apt', '>= 1.1.0'
